### ISSUE TITLE
About Dataset

### ISSUE THREAD

**Issue by osirisFdragon** [elun15/Graph-Convolutional-Network-for-Multi-Camera-Vehicle-Tracking#1]
Hi,
Can you share the dataset (S02) or a small  of it? The AI CityChallenges 2019 and 2021 ended so I cant download the dataset. Or evenly you cant share, please place the scheme/structure and the format of dataset so everyone can read the code easily.
Thanks so much for reading. Looking forward to hear your response.

**Comment by elun15** [comment]
Hello! 
Unfortunately, I do not have the right to share the dataset, but I am sure that you can write an email `to` the organizers (aicitychallenges@gmail.com) and they can provide you with the password to download the data.

The sample structure of the dataset is the following:

```
- AIC21_Track3_MTMC_Tracking/
- - validation/
- - - S02/
- - - - c006/
- - - - - gt/
- - - - - det/
- - - - - vdo.avi
- - - - - mtsc/
```
